

export const areasHomicidios = [
    {
        "id": "BR-AC",
        "value": 6390
      }, {
        "id": "BR-AL",
        "value": 5690
      }, {
        "id": "BR-AP",
        "value": 5390
      }, {
        "id": "BR-AM",
        "value": 3130
      }, {
        "id": "BR-BA",
        "value": 4510
      }, {
        "id": "BR-CE",
        "value": 5910
      }, {
        "id": "BR-DF",
        "value": 1820
      }, {
        "id": "BR-ES",
        "value": 3740
      }, {
        "id": "BR-GO",
        "value": 3930
      }, {
        "id": "BR-MA",
        "value": 2940
      }, {
        "id": "BR-MT",
        "value": 3150
      }, {
        "id": "BR-MS",
        "value": 2080
      }, {
        "id": "BR-MG",
        "value": 1960
      }, {
        "id": "BR-PA",
        "value": 2260
      }, {
        "id": "BR-PB",
        "value": 3190
      }, {
        "id": "BR-PR",
        "value": 5340
      }, {
        "id": "BR-PE",
        "value": 5730
      }, {
        "id": "BR-PI",
        "value": 2020
      }, {
        "id": "BR-RJ",
        "value": 4040
      }, {
        "id": "BR-RS",
        "value": 2670
      }, {
        "id": "BR-RO",
        "value": 2810
      }, {
        "id": "BR-RR",
        "value": 4400
      }, {
        "id": "BR-SC",
        "value": 1650
      }, {
        "id": "BR-SP",
        "value": 1070
      }, {
        "id": "BR-SE",
        "value": 5570
      }, {
        "id": "BR-TO",
        "value": 2660
      }, {
        "id": "BR-RN",
        "value": 6800
      }
]